package com.yestms.driver.android.domain.model.loads.get

import androidx.compose.runtime.Immutable

@Immutable
data class LoadModel(
    val id: Int,
    val loadId: String,
    val activationLink: String,
    val rate: Int,
    val mileage: Int,
    val commodity: String,
    val weight: Int,
    val height: Int,
    val length: Int,
    val pickUpLocation: String,
    val pickUpLat: String,
    val pickUpLng: String,
    val pickUpPolitical: String,
    val pickUpDate: String,
    val pickUpAppointment: Boolean,
    val pickUpNote: String,
    val deliveryLocation: String,
    val deliveryLat: String,
    val deliveryLng: String,
    val deliveryPolitical: String,
    val deliveryDate: String,
    val deliveryAppointment: Boolean,
    val deliveryNote: String,
    val expenses: Int,
    val notes: String,
    val createdAt: String,
    val updatedAt: String,
    val isAlert: Boolean,
    val loadStatusId: Int,
    val mcId: Int,
    val brokerId: Int,
    val driverId: Int,
    val dispatcherId: Int,
    val parentId: Int,
    val companyId: Int,
    val loadStatus: LoadStatusModel,
    val companyMcNumber: LoadsCompanyMcNumberModel,
    val broker: LoadsBrokerModel,
    val drivers: List<LoadsDriverModel>,
    val dispatcher: LoadsDispatcherModel,
    val rateCons: List<LoadsRateConsModel>,
    val mediaBols: List<LoadsMediaBolsModel>
)